### ISSUE TITLE
Resubscribe on an interval

### ISSUE THREAD

**Issue by dbrennand** [microwavekonijn/ps2census#53]
Hi,

I'm trying to use `client.resubscribe()` to rerun all subscriptions. However, I keep receiving the error:

```
TypeError: Cannot read properties of undefined (reading 'resubscribe')
    at Timeout._onTimeout (file:///usr/src/app/publisher.mjs:85:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

Here is my code:

```javascript
...
const client = new CensusClient(serviceID, 'ps2', {
    streamManager: {
        subscription: subscriptions
    },
});
...

// Configure interval to rerun all subscriptions to the websocket API
setInterval(async function (client) {
    console.log('Rerun all subscriptions.');
    await client.resubscribe(true);
}, 120000);
```

Can you shed some light as to why this might be happening?

Thanks :)

**Comment by microwavekonijn** [comment]
The functions body will use parameter client instead of the client variable from the root. As you don't inject the client into the function the parameter client will be undefined. Either remove the parameter or pass it to the parameter like:
```js
setInterval(async function (client) {
    console.log('Rerun all subscriptions.');
    await client.resubscribe(true);
}, 120000, client);
```

Also, I would run the resubscribe functionality every 5 mins or more. The `true` parameter in the resubscribe method should only be set if you encounter some error. Besides that, it is currently bugged, as I call the `unsubscribeAll` on the manager, not the stream.

**Comment by dbrennand** [comment]
> 
> 
> The functions body will use client parameter instead of the client variable from the root. As you don't inject the client into the function the client parameter will be undefined. Either remove the parameter or pass it to the parameter like:
> 
> ```js
> setInterval(async function (client) {
>     console.log('Rerun all subscriptions.');
>     await client.resubscribe();
> }, 120000, client);
> ```
> 
> Also, I would run the resubscribe functionality every 5 mins or more. The `true` parameter in the resubscribe method should only be set if you encounter some error. Besides that, it is currently bugged, as I call the `unsubscribeAll` on the manager, not the stream.

Oh my goodness I forgot to pass the `client` as the func param! Jesus it's a bad day 😞 😆 

Thanks a lot for your help and advice on removing `true` from `resubscribe` 😃 👍🏻
